apiVersion: v1
kind: Secret
type: Opaque # 8 type token tls auth config
metadata:
  name: secret-1
data:
  USER_NAME: YWRtaW4=
  PR_11: MTEx
  PASSWORD: MWYyZDFlMmU2N2Rm
  # echo -n '111' | base64    echo  'MTEx' | base64 -d
immutable: true
stringData:
  s-1: text more text

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-1-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deployment-1
  template:
    metadata:
      labels:
        app: deployment-1
    spec:
      containers:
        - name: i-1
          image: pavelk6896/10187native4-3:latest
          imagePullPolicy: Never

          ports:
            - containerPort: 8083
          envFrom:
            - secretRef:
                name: secret-1
          env:
            - name: PR_1
              valueFrom:
                secretKeyRef:
                  key: pr-1
                  name: secret-1

---
# kubectl port-forward service/service-1 8080:8083
apiVersion: v1
kind: Service
metadata:
  name: service-1
  labels:
    app: ingress-class-1
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 8083
      targetPort: 8083
      name: p-s-1
  selector:
    app: deployment-1
