apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-1-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deployment-1 #важное имя для сервиса
  template:
    metadata:
      labels:
        app: deployment-1 #имя должно совпадать
    spec:
      containers:
        - image: quay.io/jitesoft/nginx:1.21.5
          name: nginx
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80

---
# kubectl port-forward service/service-1-1 8080:80
apiVersion: v1
kind: Service
metadata:
  name: service-1-1
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: deployment-1 #указатель
  type: ClusterIP