apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  containers:
    - image: nginx:1.21
      name: nginx121
      ports:
        - containerPort: 80


---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  selector:
    name: nginx
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 30080
      name: http
  externalTrafficPolicy: Local
  type: LoadBalancer
  externalIPs:
    - 192.168.42.71

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-2
  labels:
    name: nginx
spec:
  ports:
    - port: 8081
      targetPort: 80
      nodePort: 30081
      name: http
  selector:
    name: nginx
  type: NodePort

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx
  annotations:
    nginx.ingress.kubernetes.io/default-backend: ingress-nginx-controller
    kubernetes.io/ingress.class: nginx
#    ## tells ingress to check for regex in the config file
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  defaultBackend:
    service:
      name: nginx
      port:
        number: 8080
  rules:
    - host: nginx.info.app # domain (i.e. need to change host table)
      http:
        paths: # specified path below, only be working when there is more than 1 path; If only having 1 path, it's always using / as path
          - path: /one
            pathType: Prefix
            backend:
              service:
                name: nginx # internal service
                port:
                  number: 8080 # port number that internal service exposes
          - path: /two #e($|/)(.*)
            pathType: Prefix
            backend:
              service:
                name: nginx-2
                port:
                  number: 8081