apiVersion: v1
kind: ReplicationController # традиционный (изначальный) способ организации репликации в кластере Kubernetes
metadata:
  name: replication-controller-1 # kubectl describe ReplicationController replication-controller-1 =>(Events
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: replication-controller-1
    spec:
      containers:
        - name: nginx
          image: quay.io/jitesoft/nginx:1.21.5
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80


---
# kubectl port-forward service/service-1-1 8080:80
apiVersion: v1
kind: Service
metadata:
  name: service-1-1
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: replication-controller-1 #указатель
  type: ClusterIP